"""init

Revision ID: 47fff4f82db3
Revises: 
Create Date: 2026-07-14 22:17:27.850778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fff4f82db3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgusers',
    sa.Column('tgid', sa.String(), nullable=False),
    sa.Column('register_date', sa.Integer(), nullable=False),
    sa.Column('cock_lenght', sa.Integer(), nullable=False),
    sa.Column('last_cock', sa.Integer(), nullable=False),
    sa.Column('old_cock', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tgid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgusers')
    # ### end Alembic commands ###
