"""Add streak and spam_clicks to users

Revision ID: 4e5824595dd5
Revises: 9d233742ea45
Create Date: 2026-07-29 02:31:15.960868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5824595dd5'
down_revision: Union[str, Sequence[str], None] = '9d233742ea45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tgusers', sa.Column('streak', sa.Integer(), nullable=False))
    op.add_column('tgusers', sa.Column('streak', sa.Integer(), nullable=False, server_default='0'))
    # op.add_column('tgusers', sa.Column('spam_clicks', sa.Integer(), nullable=False))
    op.add_column('tgusers', sa.Column('spam_clicks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'spam_clicks')
    op.drop_column('tgusers', 'streak')
    # ### end Alembic commands ###
