"""add_cache_records

Revision ID: 9d233742ea45
Revises: 47fff4f82db3
Create Date: 2026-07-14 22:57:45.395530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d233742ea45'
down_revision: Union[str, Sequence[str], None] = '47fff4f82db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tgid', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache_records')
    # ### end Alembic commands ###
